version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8008:8008"

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
